// src/renderer/app/components/Toggle/Toggle.vue
<template>
	<label class="Toggle" :class="{'Toggle--checked': inputChecked, 'Toggle--disabled': disabled}">
		<input type="checkbox" class="Toggle__input sr-only" :checked="model" :disabled="disabled" @change="toggle" />
		<div
			aria-hidden="true"
			class="Toggle__handle inline-flex rounded-full relative h-2 w-10 cursor-pointer bg-gray-300"
		>
			<span
				class="Toggle__handle__inner h-5 w-5 bg-gray-300 rounded-full absolute transform -translate-y-1/2 mt-1 transition transition-colors transition-transform ease-in-out duration-200"
			></span>
		</div>
	</label>
</template>

<script lang="ts">
import { Component, Model, Prop, Vue, Watch } from "vue-property-decorator";

@Component({
	data: (vm: Toggle) => ({
		inputChecked: vm.checked,
	}),
})
export default class Toggle extends Vue {
	@Model("change", { default: false }) public checked!: boolean;
	@Prop({ default: false }) public disabled!: boolean;

	private inputChecked!: boolean;

	get model() {
		return this.inputChecked;
	}

	set model(value: boolean) {
		this.inputChecked = value;
		this.$emit("change", value);
	}

	@Watch("checked")
	public onCheckedChanged(checked: boolean) {
		this.inputChecked = checked;
	}

	public toggle() {
		this.model = !this.model;
	}
}
</script>

<style lang="postcss" scoped>
.Toggle--checked .Toggle__handle__inner {
	@apply translate-x-full bg-blue-600;
}

.Toggle--disabled {
	.Toggle__handle {
		@apply cursor-not-allowed;
	}

	.Toggle__handle__inner {
		@apply border border-4 bg-white;
	}
}

.Toggle__input:focus + .Toggle__handle {
	.Toggle__handle__inner {
		@apply shadow-outline;
	}
}
</style>

// src/app/components/Toggle/Toggle.tsx
import React from "react";
import tw, { css, styled } from "twin.macro";

const Input = styled.input`
	${tw`sr-only`}
`;

const Handle = styled.div<{ disabled?: boolean }>`
	height: 5px;
	width: 30px;
	${tw`inline-flex rounded-full relative bg-theme-primary-100 dark:bg-theme-secondary-800`}

	${({ disabled }) => (disabled ? tw`cursor-not-allowed` : tw`cursor-pointer`)}
`;

const HandleInner = styled.span<{ alwaysOn?: boolean; disabled?: boolean }>`
	margin-top: 2px;
	width: 16px;
	height: 16px;
	${tw`rounded-full absolute transform -translate-y-1/2 transition transition-colors transition-transform ease-in-out duration-200`}

	${({ alwaysOn, disabled }) =>
		disabled
			? tw`bg-theme-primary-100 dark:bg-theme-secondary-800`
			: css`
					${Input} ~ ${Handle} & {
						${alwaysOn ? tw`bg-theme-primary-600` : tw`bg-theme-secondary-400 dark:bg-theme-secondary-600`}
					}

					${Input}:checked ~ ${Handle} & {
						${tw`translate-x-full bg-theme-primary-600`}
					}

					${Input}:hover ~ ${Handle} & {
						${tw`shadow-outline`}
					}

					${Input}:focus ~ ${Handle} & {
						${tw`shadow-outline`}
					}
			  `}
`;

type ToggleProps = { alwaysOn?: boolean; disabled?: boolean } & React.InputHTMLAttributes<any>;

export const Toggle = React.forwardRef<HTMLInputElement, ToggleProps>(
	({ alwaysOn, disabled, ...props }: ToggleProps, ref) => (
		<label className="flex">
			<Input type="checkbox" disabled={disabled} ref={ref} {...props} />
			<Handle disabled={disabled}>
				<HandleInner alwaysOn={alwaysOn} disabled={disabled} />
			</Handle>
		</label>
	),
);

Toggle.displayName = "Toggle";
