// src/renderer/app/ListDivided/ListDividedItem.vue
<template>
	<li
		class="flex flex-col w-full py-4 border-b border-dashed ListDividedItem border-theme-line-separator"
	>
		<div
			:class="isFloatingLabel ? 'flex-col items-start' : 'items-center'"
			class="flex justify-between"
		>
			<div class="ListDividedItem__container__label flex flex-col">
				<span
					:class="[{ 'font-semibold text-xs mb-1': isFloatingLabel }, { 'text-theme-page-text-light': !itemLabelClass }, itemLabelClass]"
					class="mr-5 ListDividedItem__label"
				>{{ label }}</span>
				<span v-if="labelDescription" :class="itemLabelDescriptionClass" class="ListDividedItem__label__description text-gray-500 text-sm">{{
					labelDescription
				}}</span>
			</div>

			<div :class="itemValueClass" class="ListDividedItem__value">
				<slot>
					<span v-if="value" class="text-theme-page-text">{{ value }}</span>
				</slot>
			</div>
		</div>
		<div v-if="$slots.content" class="mt-4">
			<slot name="content" />
		</div>
	</li>
</template>

<script lang="ts">
import { Component, Inject, Prop, Vue } from "vue-property-decorator";

@Component
export default class ListDividedItem extends Vue {
	@Prop({ required: true }) public label!: string;
	@Prop({ default: null }) public labelDescription!: string | null;
	@Prop({ default: null }) public value!: string | boolean | null;
	@Prop({ default: "" }) public itemLabelClass!: string;
	@Prop({ default: "" }) public itemLabelDescriptionClass!: string;
	@Prop({ default: "" }) public itemValueClass!: string;
	@Inject({ from: "isFloatingLabel", default: false }) public isFloatingLabel!: boolean;
}
</script>

// src/app/components/ListDivided/ListDividedItem.tsx
import React from "react";

type Props = {
	isFloatingLabel: boolean;
	labelClass: string;
	label: string;
	labelDescription: string;
	itemLabelDescriptionClass: string;
	value: string;
	itemValueClass: string;
	content: React.ReactNode;
};

export const ListDividedItem = ({
	isFloatingLabel,
	labelClass,
	label,
	labelDescription,
	itemLabelDescriptionClass,
	value,
	itemValueClass,
	content,
}: Props) => (
	<li className="flex flex-col w-full py-4 mb-5" data-testid="list-divided-item__wrapper">
		<div
			className={`flex justify-between ${isFloatingLabel ? "flex-col items-start" : "items-center"}`}
			data-testid="list-divided-item__inner-wrapper"
		>
			<div className="flex flex-col">
				<span className={`mr-5 ${labelClass}`} data-testid="list-divided-item__label">
					{label}
				</span>
				{labelDescription && (
					<span
						className={`text-sm text-theme-neutral ${itemLabelDescriptionClass}`}
						data-testid="list-divided-item__label--description"
					>
						{labelDescription}
					</span>
				)}
			</div>
			{value && (
				<div className={`${itemValueClass}`}>
					<span data-testid="list-divided-item__value">{value}</span>
				</div>
			)}
		</div>
		{content && (
			<div className="mt-4" data-testid="list-divided-item__content">
				{content}
			</div>
		)}
	</li>
);
