// src/app/components/Pagination/Pagination.tsx
import { Button } from "app/components/Button";
import { Icon } from "app/components/Icon";
import React, { useMemo } from "react";
import { useTranslation } from "react-i18next";
import tw, { styled } from "twin.macro";

import { CompactPagination } from "./components/CompactPagination";

const Wrapper = styled.div`
	${tw`flex space-x-3 h-10`}

	button:first-child,button:last-child {
		${tw``}
	}

	button {
		${tw`py-2 px-4`}
	}
`;

type PaginationProps = {
	totalCount: number;
	itemsPerPage: number;
	onSelectPage: any;
	currentPage: number;
	className?: string;
	variant?: "condensed";
};

const PaginationButton = styled.div`
	${tw`text-theme-primary-500 dark:text-theme-secondary-200 cursor-pointer px-2 text-base inline-flex items-center font-semibold text-center transition-all duration-100 ease-linear justify-center`}

	&:not(:disabled):hover {
		${tw`bg-theme-primary-600 text-white rounded`}
		box-shadow: 2px 3px 10px 2px rgba(var(--theme-color-primary-rgb), 0.2);
		transform: scale(1.1);
	}

	&.current-page {
		${tw`bg-theme-primary-200 dark:bg-theme-secondary-600 text-theme-primary-500 dark:text-theme-secondary-200`}
	}
`;

const PaginationSearchButton = styled.div`
	${tw`relative text-theme-primary-500 p-3 cursor-pointer flex flex-nowrap items-center dark:text-theme-secondary-200`}

	&:hover {
		${tw`bg-theme-primary-600 text-white rounded`}
		box-shadow: 2px 3px 10px 2px rgba(var(--theme-color-primary-rgb), 0.2);
		transform: scale(1.1);
	}
`;

export const Pagination = ({
	totalCount,
	itemsPerPage,
	onSelectPage,
	currentPage,
	className,
	variant,
}: PaginationProps) => {
	const { t } = useTranslation();

	const totalPages = Math.ceil(totalCount / itemsPerPage);

	const buttonCount = useMemo(() => (currentPage < 100 ? 7 : 5), [currentPage]);
	const subRangeLength = useMemo(() => Math.floor(buttonCount / 2), [buttonCount]);

	const paginationButtons = useMemo(() => {
		let buttons;

		if (totalPages <= buttonCount) {
			buttons = Array(...Array(totalPages)).map((_, i) => i + 1);
		} else if (currentPage <= subRangeLength + 1) {
			buttons = Array(...Array(buttonCount)).map((_, i) => i + 1);
		} else if (currentPage >= totalPages - subRangeLength) {
			buttons = Array(...Array(buttonCount)).map((_, i) => totalPages - buttonCount + i + 1);
		} else {
			buttons = Array(...Array(buttonCount)).map((_, i) => currentPage - subRangeLength + i);
		}

		return buttons;
	}, [currentPage, totalPages, buttonCount, subRangeLength]);

	const showFirst = useMemo(() => !paginationButtons.includes(1), [paginationButtons]);
	const showPrevious = useMemo(() => currentPage > 1, [currentPage]);
	const showNext = useMemo(() => currentPage < totalPages, [currentPage, totalPages]);
	const showLast = useMemo(() => totalPages !== currentPage + 1 && !paginationButtons.includes(totalPages), [
		currentPage,
		totalPages,
		paginationButtons,
	]);

	if (variant === "condensed") {
		return (
			<CompactPagination
				totalCount={totalCount}
				itemsPerPage={itemsPerPage}
				onSelectPage={onSelectPage}
				currentPage={currentPage}
			/>
		);
	}

	return (
		<Wrapper data-testid="Pagination" className={className}>
			{showFirst && (
				<Button
					data-testid="Pagination__first"
					variant="secondary"
					onClick={() => onSelectPage((currentPage = 1))}
				>
					<Icon name="PaginationFirst" height={12} width={12} />
				</Button>
			)}

			{showPrevious && (
				<Button
					data-testid="Pagination__previous"
					variant="secondary"
					onClick={() => onSelectPage((currentPage -= 1))}
				>
					<Icon name="Back" className="mr-2" height={10} width={10} />
					{t("COMMON.PREVIOUS")}
				</Button>
			)}

			<div className="flex px-2 rounded bg-theme-primary-100 dark:bg-theme-secondary-800">
				{paginationButtons[0] !== 1 && (
					<PaginationSearchButton>
						<span>...</span>
					</PaginationSearchButton>
				)}

				{paginationButtons.map((page) => (
					<PaginationButton
						key={page}
						className={currentPage === page ? "current-page" : ""}
						onClick={() => onSelectPage(page)}
					>
						{page}
					</PaginationButton>
				))}

				{paginationButtons[paginationButtons.length - 1] !== totalPages && (
					<PaginationSearchButton>
						<span>...</span>
					</PaginationSearchButton>
				)}
			</div>

			{showNext && (
				<Button
					data-testid="Pagination__next"
					variant="secondary"
					onClick={() => onSelectPage((currentPage += 1))}
				>
					{t("COMMON.NEXT")}
					<Icon name="Forward" className="ml-2" height={12} width={12} />
				</Button>
			)}

			{showLast && (
				<Button
					data-testid="Pagination__last"
					variant="secondary"
					onClick={() => onSelectPage((currentPage = totalPages))}
				>
					<Icon name="PaginationLast" height={12} width={12} />
				</Button>
			)}
		</Wrapper>
	);
};

Pagination.defaultProps = {
	currentPage: 1,
	itemsPerPage: 4,
};

// src/renderer/components/Pagination/Pagination.vue
<template>
  <div
    v-click-outside="closePageInput"
    class="Pagination mx-5 sm:mx-10 mt-5 md:mt-10"
  >
    <div class="PaginationBar--small relative">
      <PaginationPageInput
        :is-visible="showPageInput"
        :page-count="pageCount"
        :is-mobile="isMobile"
        class="Pagination__Input"
        @page-change="emitPageChange"
        @close="closePageInput"
      />

      <PaginationSearchButton
        :class="{ 'opacity-0': showPageInput }"
        class="w-full justify-center"
        :hover-scale="false"
        @click="openPageInput"
      >
        {{ $t('PAGINATION.PAGE') }} {{ currentPage }} {{ $t('PAGINATION.OF') }} {{ pageCount }}
      </PaginationSearchButton>
    </div>

    <div class="flex justify-center">
      <PaginationNavigationButton
        :is-visible="showFirst"
        type="first"
        class="mr-2"
        @click="emitFirst"
      />

      <PaginationNavigationButton
        :is-visible="showPrevious"
        type="previous"
        class="mr-2"
        @click="emitPrevious"
      />

      <div class="PaginationBar--large relative">
        <PaginationPageInput
          :is-visible="showPageInput"
          :page-count="pageCount"
          :is-mobile="isMobile"
          class="Pagination__Input"
          @page-change="emitPageChange"
          @close="closePageInput"
        />

        <div
          :class="{ 'opacity-0': showPageInput }"
          class="hidden md:flex px-3 bg-theme-button rounded"
        >
          <PaginationSearchButton
            :is-visible="pageButtons[0] !== 1"
            @click="openPageInput"
          />

          <button
            v-for="page in pageButtons"
            :key="page"
            :disabled="page === currentPage"
            :class="{ 'active': page === currentPage }"
            class="Pagination__Button transition"
            @click="emitPageChange(page)"
          >
            <span>{{ page }}</span>
          </button>

          <PaginationSearchButton
            :is-visible="pageButtons[pageButtons.length - 1] !== pageCount"
            @click="openPageInput"
          />
        </div>

        <div class="flex md:hidden bg-theme-button rounded">
          <PaginationSearchButton
            :hover-scale="false"
            :class="{ 'opacity-0': showPageInput }"
            @click="openPageInput"
          >
            {{ $t('PAGINATION.PAGE') }} {{ currentPage }} {{ $t('PAGINATION.OF') }} {{ pageCount }}
          </PaginationSearchButton>
        </div>
      </div>

      <PaginationNavigationButton
        :is-visible="showNext"
        type="next"
        class="ml-2"
        @click="emitNext"
      />

      <PaginationNavigationButton
        :is-visible="showLast"
        type="last"
        class="ml-2"
        @click="emitLast"
      />
    </div>
  </div>
</template>

<script>
import {
  PaginationNavigationButton,
  PaginationPageInput,
  PaginationSearchButton
} from '@/components/Pagination'

export default {
  name: 'Pagination',

  components: {
    PaginationNavigationButton,
    PaginationPageInput,
    PaginationSearchButton
  },

  props: {
    meta: {
      type: Object,
      required: true
    },

    currentPage: {
      type: Number,
      required: true
    }
  },

  data: () => ({
    pageInputVisible: false,
    mobileView: false
  }),

  computed: {
    showPageInput () {
      return this.pageInputVisible
    },

    buttonCount () {
      return this.currentPage < 100 ? 7 : 5
    },

    pageCount () {
      return this.meta.pageCount
    },

    next () {
      return this.meta.next
    },

    previous () {
      return this.meta.previous
    },

    self () {
      return this.meta.self
    },

    first () {
      return this.meta.first
    },

    last () {
      return this.meta.last
    },

    showFirst () {
      return (this.first !== this.previous && !this.pageButtons.includes(1)) || (this.first !== this.self && this.isMobile)
    },

    showPrevious () {
      return this.currentPage > 1
    },

    showNext () {
      return this.currentPage < this.pageCount
    },

    showLast () {
      return (this.last !== this.next && !this.pageButtons.includes(this.pageCount)) || (this.last !== this.self && this.isMobile)
    },

    subRangeLength () {
      return Math.floor(this.buttonCount / 2)
    },

    pageButtons () {
      let buttons

      if (this.pageCount <= this.buttonCount) {
        buttons = Array.apply(null, Array(this.pageCount)).map((_, i) => i + 1)
      } else if (this.currentPage <= this.subRangeLength + 1) {
        buttons = Array.apply(null, Array(this.buttonCount)).map((_, i) => i + 1)
      } else if (this.currentPage >= this.pageCount - this.subRangeLength) {
        buttons = Array.apply(null, Array(this.buttonCount)).map((_, i) => {
          return this.pageCount - this.buttonCount + i + 1
        })
      } else {
        buttons = Array.apply(null, Array(this.buttonCount)).map((_, i) => {
          return this.currentPage - this.subRangeLength + i
        })
      }

      return buttons
    },

    isMobile () {
      return this.mobileView
    }
  },

  mounted () {
    const WIDTH_THRESHOLD = 768
    const widthQuery = window.matchMedia(`(max-width: ${WIDTH_THRESHOLD}px)`)

    widthQuery.addListener(e => this.setMobileView(e.matches))

    this.setMobileView(window.innerWidth < WIDTH_THRESHOLD)
  },

  methods: {
    emitFirst () {
      this.emitPageChange(1)
    },

    emitPrevious () {
      this.emitPageChange(this.currentPage - 1)
    },

    emitNext () {
      this.emitPageChange(this.currentPage + 1)
    },

    emitLast () {
      this.emitPageChange(this.pageCount)
    },

    emitPageChange (page) {
      this.$emit('page-change', page)
    },

    openPageInput () {
      this.pageInputVisible = true
    },

    closePageInput () {
      this.pageInputVisible = false
    },

    setMobileView (isMobile) {
      this.mobileView = !!isMobile
    }
  }
}
</script>

<style lang="postcss" scoped>
.Pagination {
  @apply .flex .flex-col .flex-no-wrap .justify-center;
}

.Pagination__Button {
  @apply .text-theme-button-text .p-3 .cursor-pointer .flex .flex-no-wrap .items-center;
}

button[class*="Pagination__Button--"] {
  @apply .flex-1;
}

.Pagination__Button.active {
  @apply .bg-theme-button-active .text-theme-button-text;
}

.Pagination__Button:not(:disabled):hover {
  @apply .bg-blue .text-white .rounded;
  box-shadow: 0 5px 15px rgba(9, 100, 228, 0.34);
  -webkit-transform: scale(1.1);
  transform: scale(1.1);
}

.Pagination__Button:disabled {
  @apply .text-theme-button-text;
}

.PaginationBar--small {
  @apply .hidden .bg-theme-button .rounded .mb-2;
}

.PaginationBar--small {
  @apply .flex;
}

.PaginationBar--large {
  @apply .hidden;
}

@media (min-width: 450px) {
  button[class*="Pagination__Button--"] {
    @apply .flex-none;
  }

  .PaginationBar--small {
    @apply .hidden;
  }

  .PaginationBar--large {
    @apply .flex;
  }
}
</style>
